on:
  push:
    branches:
    - master

jobs:
  deploy:
    name: Deploy to live
    runs-on: macos-latest
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '14'
      
    - name: npm install and deploy
      run: |
        npm ci
        npm run deploy
